# Generated by Django 4.2.1 on 2023-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('role', models.CharField(max_length=20)),
                ('recommend', models.CharField(max_length=4)),
                ('skill', models.CharField(max_length=20)),
                ('reviews', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
