# Generated by Django 4.2.1 on 2023-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_contact_prediction_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='recommend',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='skill',
        ),
        migrations.AddField(
            model_name='contact',
            name='sentiment_score',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
