# Generated by Django 4.2.1 on 2023-06-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_contact_sentiment_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sentiment_score',
            new_name='sentimentscore',
        ),
    ]
